### ISSUE TITLE
'Monters' directory instructions missing from README

### ISSUE THREAD

**Issue by SeeingBlue** [jlnunez89/fibula-mmo#44]
Before the server will launch, it checks for the 'monters' directory which is not created and does not exist. The server will not launch.

Nothing in the setup guide says this directory needs to be created.
Once it is created, the server will launch.
I also suspect the directory is a typo so I've submitted a pull request to correct this.

**Comment by jlnunez89** [comment]
Yeah, I just added the monsters bit not so long ago and didn't update the readme. I also merged your PR. I appreciate you fixing it! :)

**Comment by jlnunez89** [comment]
decided to include the monsters in the project, closing this now.
