### ISSUE TITLE
Client crash: Error while sending CreatureMovedNotification. Full error inside.

### ISSUE THREAD

**Issue by nielss94** [jlnunez89/fibula-mmo#48]
Start server. Logged in. Few seconds after walking the client crashed: 

[Error] OpenTibia.Server.Notifications.CreatureMovedNotification: Error while sending CreatureMovedNotification: creatureMetadata has an invalid race Id 32. No monster could be created.

**Comment by jlnunez89** [comment]
Please git pull and try again, added monster files for the sake of avoiding confusion.

**Comment by nielss94** [comment]
That solved it! Nice!

**Comment by jlnunez89** [comment]
cool, closing now.
