### ISSUE TITLE
Server crash: System.ArgumentNullException: Value cannot be null. (Parameter 'value')

### ISSUE THREAD

**Issue by nielss94** [jlnunez89/fibula-mmo#49]
When I logged in again after getting the client crashed caused by #48 , walked about 20 sqm and then the server crashed.

Unhandled exception. [17:02:55] [Debug] OpenTibia.Server.Game: Processed event 826d62e27ff14f9a9d25718c36664863, current game time: 1578844975109.
System.ArgumentNullException: Value cannot be null. (Parameter 'value')

**Comment by jlnunez89** [comment]
Let me know if you can still repro after git pulling the latest PR (#50).

**Comment by nielss94** [comment]
That solved it! Nice!

**Comment by jlnunez89** [comment]
closing as issue is solved :)
