### ISSUE TITLE
Items intermittently fail to visually update on move.

### ISSUE THREAD

**Issue by SeeingBlue** [jlnunez89/fibula-mmo#54]
The house to the NW of the Thais depot is open and contains a stack of dragon ham, skulls, and burst arrows. Go attempt to move those 3 items around on the ground. 

Every so often a move will fail to visually update. When this happens you can move another item, move the same item again, or walk 1sqm and the update will occur.

EDIT: Does not have to be a stacked item, sometimes things just fail to visually update when moving them on the ground.

**Comment by jlnunez89** [comment]
I believe this is now addressed but I could not clearly reproduce it. I did see some bugs with how stack-able items were being split/merged back but I fixed that in #64. 
Please re open if you find this is not addressed completely :)
