### ISSUE TITLE
OTClient: Failed event condition LocationNotObstructedEventCondition

### ISSUE THREAD

**Issue by SeeingBlue** [jlnunez89/fibula-mmo#58]
When using the keyboard to walk fast, it will produce an error.

`[23:51:01] [Debug] OpenTibia.Server.MovementEvents.MapToMapMovementEvent: Failed event condition LocationNotObstructedEventCondition.`

You also see error in-game that says `There is not enough room.`

**Comment by jlnunez89** [comment]
Conditions are no longer separate after #71, so this is no longer in scope.
