### ISSUE TITLE
OTClient disconnects from game

### ISSUE THREAD

**Issue by SeeingBlue** [jlnunez89/fibula-mmo#68]
Any client OTclient disconnects from the game every 30 seconds. I suspect this is due to a ping the client is looking for and does not receive from the server.

**Comment by jlnunez89** [comment]
Do you happen to know the packet structure expected by OTClient on these pings? Or can you point to some implementation of it in 7.72 ? A quick skim through OTLand yielded some results but I haven't really dissected any of them, as it isn't very high in my priority list.

I tried adding a ping back but it seems the OTClient expects a ping (without sending one) from the server. I'm unsure what these server initiated pings look like, byte wise. I'm planning to add these to the connection sweeper thread I got running on the main loop.

**Comment by SeeingBlue** [comment]
I don't know. It was only suggested to me that this was the cause and I just expected it was normal ping/pong between the server that it was looking for.

**Comment by jlnunez89** [comment]
Discontinued support of vanilla client in favor of OTC, which now no longer disconnects.
