### ISSUE TITLE
[Question] RSA Decryption increases CPU usage by 0.1%

### ISSUE THREAD

**Issue by TwistedScorpio** [jlnunez89/fibula-mmo#73]
This is just something I've noticed, when I spam logging on the server my 16 cores AMD Ryzen 2700X CPU usage rises to 0.1%, even if it's a single logging attempt, imagine that it's over 300 players at a time spamming the login queue?

**Comment by jlnunez89** [comment]
Thanks for the feedback! However, I'm closing this as it is not actionable for 2 reasons:

1) The BigInteger class responsible for RSA decryption was replaced by an industry accepted standard.

2) There is not enough information about the methodology followed in your test to suggest there is a change needed, or that effort needs to go into further optimization. If it becomes a problem it'll be looked into, but it doesn't sound like it at the time.
